[alembic]
script_location = alembic
sqlalchemy.url = postgresql://postgres:postgres123@localhost:5432/construction_db

[post_write_hooks]

[loggers]
keys = root,sentinel,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sentinel]
level = INFO
handlers = console
qualname = sentinel

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
